volumes:
  redis_data:

services:
  redis:
    container_name: redis
    image: redis/redis-stack:7.2.0-v13
    ports:
      - "6379:6379"
      - "8001:8001"
    command: [ "/entrypoint.sh", "./redis-stack.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
