networks:
  net:

volumes:
  redis_data:

services:
  redis:
    container_name: redis
    image: redis/redis-stack:7.2.0-v13
    command: [ "/entrypoint.sh", "./redis-stack.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - net
    volumes:
      - redis_data:/data

  task-queue-backend:
    container_name: task_queue_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    networks:
      - net
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
